/* Generated by cli_gen_tool version <1.0>; using InputHandler version <0.9a> */
/**
 * @file functions.h
 * @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
 * @brief InputHandler autogenerated functions.h
 * @version 1.0
 * @date 2023-02-24
 *
 * @copyright Copyright (c) 2023
 */
/*
 * Copyright (c) 2023 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
 *
 * License: GNU GPL3
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 3 as published by the Free Software Foundation.
 */

#if !defined(__FUNCTIONS_H__)
    #define __FUNCTIONS_H__
    #include "InputHandler.h"

/* InputHandler user return function prototypes */

/* InputHandler builtin functions */

void unrecognized(ih::Input* _inputHandler) { _inputHandler->outputToStream(Serial); }
void listCommands(ih::Input* _inputHandler) { _inputHandler->listCommands(); }
void listSettings(ih::Input* _inputHandler) { _inputHandler->listSettings(); }

/* InputHandler user defined functions */

#endif

// end of file
