/* Generated by InputHandler's /InputHandler/cli_gen_tool/cli_gen_tool.py version 1.0 */
/**
* @file functions.h
* @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
* @brief InputHandler autogenerated functions.h
* @version 1.0
* @date 2022-12-30
*
* @copyright Copyright (c) 2022
*/
/*
* Copyright (c) 2022 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* version 3 as published by the Free Software Foundation.
*/


#if !defined(__FUNCTIONS_H__)
    #define __FUNCTIONS_H__
    #include "cli_InputHandler.h"
    

/* InputHandler user return function prototypes */
extern void test(UserInput* _inputHandler);
extern void testa(UserInput* _inputHandler);
extern void testb(UserInput* _inputHandler);
extern void testc(UserInput* _inputHandler);
extern void test(UserInput* _inputHandler);
extern void testbb_return_values(UserInput* _inputHandler);

void unrecognized(UserInput* _inputHandler)
{
  _inputHandler->outputToStream(Serial);
}

void listCommands(UserInput* _inputHandler)
{
  _inputHandler->listCommands();
}

void listSettings(UserInput* _inputHandler)
{
  _inputHandler->listSettings(_inputHandler);
}

void test_2(UserInput* _inputHandler)
{
  test(_inputHandler);
}

void testa_3(UserInput* _inputHandler)
{
  testa(_inputHandler);
}

void testd_5(UserInput* _inputHandler)
{
  testb(_inputHandler);
}

void teste_6(UserInput* _inputHandler)
{
  testc(_inputHandler);
}

void testbb_7(UserInput* _inputHandler)
{
  testbb_return_values(_inputHandler);
}




#endif

// end of file
