# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QHeaderView, QLabel,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QTreeView, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1413, 892)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionInputHandler_Documentation = QAction(MainWindow)
        self.actionInputHandler_Documentation.setObjectName(u"actionInputHandler_Documentation")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionGenerate_CLI_Files = QAction(MainWindow)
        self.actionGenerate_CLI_Files.setObjectName(u"actionGenerate_CLI_Files")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1421, 871))
        self.tabWidget.setAutoFillBackground(True)
        self.ih_settings_tab = QWidget()
        self.ih_settings_tab.setObjectName(u"ih_settings_tab")
        self.settings_table = QTableWidget(self.ih_settings_tab)
        if (self.settings_table.columnCount() < 2):
            self.settings_table.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.settings_table.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.settings_table.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.settings_table.setObjectName(u"settings_table")
        self.settings_table.setGeometry(QRect(10, 20, 771, 761))
        self.settings_table.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.settings_table.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.settings_table.horizontalHeader().setVisible(False)
        self.settings_table.horizontalHeader().setCascadingSectionResizes(False)
        self.settings_table.horizontalHeader().setMinimumSectionSize(50)
        self.settings_table.horizontalHeader().setDefaultSectionSize(350)
        self.settings_table.horizontalHeader().setStretchLastSection(False)
        self.editButton_1 = QPushButton(self.ih_settings_tab)
        self.editButton_1.setObjectName(u"editButton_1")
        self.editButton_1.setGeometry(QRect(190, 790, 121, 31))
        self.defaultButton_1 = QPushButton(self.ih_settings_tab)
        self.defaultButton_1.setObjectName(u"defaultButton_1")
        self.defaultButton_1.setGeometry(QRect(450, 790, 121, 31))
        self.clearButton_1 = QPushButton(self.ih_settings_tab)
        self.clearButton_1.setObjectName(u"clearButton_1")
        self.clearButton_1.setGeometry(QRect(320, 790, 121, 31))
        self.tab_1_code_preview_label = QLabel(self.ih_settings_tab)
        self.tab_1_code_preview_label.setObjectName(u"tab_1_code_preview_label")
        self.tab_1_code_preview_label.setGeometry(QRect(1070, 0, 121, 21))
        self.codePreview_1 = QTreeView(self.ih_settings_tab)
        self.codePreview_1.setObjectName(u"codePreview_1")
        self.codePreview_1.setGeometry(QRect(790, 20, 611, 801))
        self.codePreview_1.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tab_1_settings_table_label = QLabel(self.ih_settings_tab)
        self.tab_1_settings_table_label.setObjectName(u"tab_1_settings_table_label")
        self.tab_1_settings_table_label.setGeometry(QRect(330, 0, 121, 21))
        self.tabWidget.addTab(self.ih_settings_tab, "")
        self.command_tab = QWidget()
        self.command_tab.setObjectName(u"command_tab")
        self.command_tree = QTreeView(self.command_tab)
        self.command_tree.setObjectName(u"command_tree")
        self.command_tree.setGeometry(QRect(10, 20, 771, 761))
        self.command_tree.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.command_tree.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.command_tree.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tab_2_code_preview_label = QLabel(self.command_tab)
        self.tab_2_code_preview_label.setObjectName(u"tab_2_code_preview_label")
        self.tab_2_code_preview_label.setGeometry(QRect(1070, 0, 121, 21))
        self.codePreview_2 = QTreeView(self.command_tab)
        self.codePreview_2.setObjectName(u"codePreview_2")
        self.codePreview_2.setGeometry(QRect(790, 20, 611, 801))
        self.codePreview_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.deleteButton_2 = QPushButton(self.command_tab)
        self.deleteButton_2.setObjectName(u"deleteButton_2")
        self.deleteButton_2.setGeometry(QRect(450, 790, 121, 31))
        self.editButton_2 = QPushButton(self.command_tab)
        self.editButton_2.setObjectName(u"editButton_2")
        self.editButton_2.setGeometry(QRect(320, 790, 121, 31))
        self.newButton_2 = QPushButton(self.command_tab)
        self.newButton_2.setObjectName(u"newButton_2")
        self.newButton_2.setGeometry(QRect(190, 790, 121, 31))
        self.tab_2_command_tree_label = QLabel(self.command_tab)
        self.tab_2_command_tree_label.setObjectName(u"tab_2_command_tree_label")
        self.tab_2_command_tree_label.setGeometry(QRect(320, 0, 121, 21))
        self.tabWidget.addTab(self.command_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1413, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuGenerate = QMenu(self.menubar)
        self.menuGenerate.setObjectName(u"menuGenerate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGenerate.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionInputHandler_Documentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuGenerate.addAction(self.actionGenerate_CLI_Files)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"InputHandler CLI generation tool", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
#if QT_CONFIG(shortcut)
        self.actionPreferences.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionInputHandler_Documentation.setText(QCoreApplication.translate("MainWindow", u"InputHandler Documentation", None))
#if QT_CONFIG(shortcut)
        self.actionInputHandler_Documentation.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionGenerate_CLI_Files.setText(QCoreApplication.translate("MainWindow", u"Generate CLI Files", None))
#if QT_CONFIG(shortcut)
        self.actionGenerate_CLI_Files.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        ___qtablewidgetitem = self.settings_table.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Option", None));
        ___qtablewidgetitem1 = self.settings_table.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Setting", None));
        self.editButton_1.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.defaultButton_1.setText(QCoreApplication.translate("MainWindow", u"Default", None))
        self.clearButton_1.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.tab_1_code_preview_label.setText(QCoreApplication.translate("MainWindow", u"Code Preview", None))
        self.tab_1_settings_table_label.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ih_settings_tab), QCoreApplication.translate("MainWindow", u"InputHandler Settings", None))
        self.tab_2_code_preview_label.setText(QCoreApplication.translate("MainWindow", u"Code Preview", None))
        self.deleteButton_2.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.editButton_2.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.newButton_2.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.tab_2_command_tree_label.setText(QCoreApplication.translate("MainWindow", u"Commands", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.command_tab), QCoreApplication.translate("MainWindow", u"Command Tree", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuGenerate.setTitle(QCoreApplication.translate("MainWindow", u"Generate", None))
    # retranslateUi

