# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QCheckBox, QComboBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QSpinBox, QTabWidget, QTextEdit, QTreeView,
    QTreeWidget, QTreeWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1420, 875)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1420, 875))
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionInputHandler_Documentation = QAction(MainWindow)
        self.actionInputHandler_Documentation.setObjectName(u"actionInputHandler_Documentation")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionGenerate_CLI_Files = QAction(MainWindow)
        self.actionGenerate_CLI_Files.setObjectName(u"actionGenerate_CLI_Files")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(1420, 850))
        self.centralwidget.setLayoutDirection(Qt.LeftToRight)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1420, 850))
        self.tabWidget.setMinimumSize(QSize(1420, 850))
        self.tabWidget.setSizeIncrement(QSize(0, 0))
        self.tabWidget.setAutoFillBackground(True)
        self.ih_settings_tab = QWidget()
        self.ih_settings_tab.setObjectName(u"ih_settings_tab")
        self.editButton_1 = QPushButton(self.ih_settings_tab)
        self.editButton_1.setObjectName(u"editButton_1")
        self.editButton_1.setGeometry(QRect(190, 790, 121, 31))
        self.defaultButton_1 = QPushButton(self.ih_settings_tab)
        self.defaultButton_1.setObjectName(u"defaultButton_1")
        self.defaultButton_1.setGeometry(QRect(450, 790, 121, 31))
        self.clearButton_1 = QPushButton(self.ih_settings_tab)
        self.clearButton_1.setObjectName(u"clearButton_1")
        self.clearButton_1.setGeometry(QRect(320, 790, 121, 31))
        self.tab_1_code_preview_label = QLabel(self.ih_settings_tab)
        self.tab_1_code_preview_label.setObjectName(u"tab_1_code_preview_label")
        self.tab_1_code_preview_label.setGeometry(QRect(1070, 0, 121, 21))
        self.codePreview_1 = QTreeView(self.ih_settings_tab)
        self.codePreview_1.setObjectName(u"codePreview_1")
        self.codePreview_1.setGeometry(QRect(790, 20, 611, 801))
        self.codePreview_1.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tab_1_settings_table_label = QLabel(self.ih_settings_tab)
        self.tab_1_settings_table_label.setObjectName(u"tab_1_settings_table_label")
        self.tab_1_settings_table_label.setGeometry(QRect(330, 0, 121, 21))
        self.settings_tree = QTreeWidget(self.ih_settings_tab)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.settings_tree.setHeaderItem(__qtreewidgetitem)
        self.settings_tree.setObjectName(u"settings_tree")
        self.settings_tree.setGeometry(QRect(10, 20, 771, 761))
        self.settings_tree.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.settings_tree.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.settings_tree.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tabWidget.addTab(self.ih_settings_tab, "")
        self.command_tab = QWidget()
        self.command_tab.setObjectName(u"command_tab")
        self.command_tree = QTreeWidget(self.command_tab)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"1");
        self.command_tree.setHeaderItem(__qtreewidgetitem1)
        self.command_tree.setObjectName(u"command_tree")
        self.command_tree.setGeometry(QRect(10, 20, 771, 631))
        self.command_tree.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.command_tree.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.command_tree.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tab_2_code_preview_label = QLabel(self.command_tab)
        self.tab_2_code_preview_label.setObjectName(u"tab_2_code_preview_label")
        self.tab_2_code_preview_label.setGeometry(QRect(1070, 0, 121, 21))
        self.codePreview_2 = QTreeView(self.command_tab)
        self.codePreview_2.setObjectName(u"codePreview_2")
        self.codePreview_2.setGeometry(QRect(790, 20, 611, 801))
        self.codePreview_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.deleteButton_2 = QPushButton(self.command_tab)
        self.deleteButton_2.setObjectName(u"deleteButton_2")
        self.deleteButton_2.setGeometry(QRect(450, 790, 121, 31))
        self.editButton_2 = QPushButton(self.command_tab)
        self.editButton_2.setObjectName(u"editButton_2")
        self.editButton_2.setGeometry(QRect(320, 790, 121, 31))
        self.newButton_2 = QPushButton(self.command_tab)
        self.newButton_2.setObjectName(u"newButton_2")
        self.newButton_2.setGeometry(QRect(190, 790, 121, 31))
        self.tab_2_command_tree_label = QLabel(self.command_tab)
        self.tab_2_command_tree_label.setObjectName(u"tab_2_command_tree_label")
        self.tab_2_command_tree_label.setGeometry(QRect(320, 0, 121, 21))
        self.command_settings = QWidget(self.command_tab)
        self.command_settings.setObjectName(u"command_settings")
        self.command_settings.setGeometry(QRect(0, 660, 781, 131))
        self.textEdit = QTextEdit(self.command_settings)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(400, 20, 381, 101))
        self.spinBox_4 = QSpinBox(self.command_settings)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(350, 80, 41, 21))
        self.commandMinArgs = QSpinBox(self.command_settings)
        self.commandMinArgs.setObjectName(u"commandMinArgs")
        self.commandMinArgs.setGeometry(QRect(350, 60, 41, 21))
        self.commandDepth = QSpinBox(self.command_settings)
        self.commandDepth.setObjectName(u"commandDepth")
        self.commandDepth.setGeometry(QRect(350, 0, 41, 21))
        self.spinBox = QSpinBox(self.command_settings)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(350, 20, 41, 21))
        self.commandParentId = QLineEdit(self.command_settings)
        self.commandParentId.setObjectName(u"commandParentId")
        self.commandParentId.setGeometry(QRect(100, 60, 113, 20))
        self.commandString = QLineEdit(self.command_settings)
        self.commandString.setObjectName(u"commandString")
        self.commandString.setGeometry(QRect(100, 20, 113, 20))
        self.commandLengthLabel = QLabel(self.command_settings)
        self.commandLengthLabel.setObjectName(u"commandLengthLabel")
        self.commandLengthLabel.setGeometry(QRect(100, 40, 47, 21))
        self.functionName = QLineEdit(self.command_settings)
        self.functionName.setObjectName(u"functionName")
        self.functionName.setGeometry(QRect(100, 0, 113, 20))
        self.checkBox = QCheckBox(self.command_settings)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(100, 100, 111, 21))
        self.label_2 = QLabel(self.command_settings)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 0, 81, 21))
        self.label_3 = QLabel(self.command_settings)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 0, 81, 21))
        self.label_4 = QLabel(self.command_settings)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 81, 21))
        self.label_5 = QLabel(self.command_settings)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 40, 81, 21))
        self.label_6 = QLabel(self.command_settings)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 60, 47, 16))
        self.commandId = QLineEdit(self.command_settings)
        self.commandId.setObjectName(u"commandId")
        self.commandId.setGeometry(QRect(100, 80, 113, 20))
        self.label_7 = QLabel(self.command_settings)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 80, 47, 16))
        self.commandSubcommands = QLabel(self.command_settings)
        self.commandSubcommands.setObjectName(u"commandSubcommands")
        self.commandSubcommands.setGeometry(QRect(220, 20, 81, 21))
        self.label_9 = QLabel(self.command_settings)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(220, 60, 51, 21))
        self.commandMaxArgs = QLabel(self.command_settings)
        self.commandMaxArgs.setObjectName(u"commandMaxArgs")
        self.commandMaxArgs.setGeometry(QRect(220, 80, 51, 21))
        self.commandArgumentHandling = QComboBox(self.command_settings)
        self.commandArgumentHandling.addItem("")
        self.commandArgumentHandling.addItem("")
        self.commandArgumentHandling.addItem("")
        self.commandArgumentHandling.setObjectName(u"commandArgumentHandling")
        self.commandArgumentHandling.setGeometry(QRect(220, 40, 171, 20))
        self.label = QLabel(self.command_settings)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(500, 0, 211, 16))
        self.tabWidget.addTab(self.command_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1420, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuGenerate = QMenu(self.menubar)
        self.menuGenerate.setObjectName(u"menuGenerate")
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGenerate.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInputHandler_Documentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuGenerate.addAction(self.actionGenerate_CLI_Files)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"InputHandler CLI generation tool", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
#if QT_CONFIG(shortcut)
        self.actionPreferences.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionInputHandler_Documentation.setText(QCoreApplication.translate("MainWindow", u"InputHandler Documentation", None))
#if QT_CONFIG(shortcut)
        self.actionInputHandler_Documentation.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionGenerate_CLI_Files.setText(QCoreApplication.translate("MainWindow", u"Generate CLI Files", None))
#if QT_CONFIG(shortcut)
        self.actionGenerate_CLI_Files.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.editButton_1.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.defaultButton_1.setText(QCoreApplication.translate("MainWindow", u"Default", None))
        self.clearButton_1.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.tab_1_code_preview_label.setText(QCoreApplication.translate("MainWindow", u"Code Preview", None))
        self.tab_1_settings_table_label.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ih_settings_tab), QCoreApplication.translate("MainWindow", u"InputHandler Settings", None))
        self.tab_2_code_preview_label.setText(QCoreApplication.translate("MainWindow", u"Code Preview", None))
        self.deleteButton_2.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.editButton_2.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.newButton_2.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.tab_2_command_tree_label.setText(QCoreApplication.translate("MainWindow", u"Commands", None))
        self.commandLengthLabel.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Contains Wildcards", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Function name", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Command depth", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Command string", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Command length", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Parent id", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"id", None))
        self.commandSubcommands.setText(QCoreApplication.translate("MainWindow", u"Subcommands", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Min. args.", None))
        self.commandMaxArgs.setText(QCoreApplication.translate("MainWindow", u"Max args.", None))
        self.commandArgumentHandling.setItemText(0, QCoreApplication.translate("MainWindow", u"No arguments", None))
        self.commandArgumentHandling.setItemText(1, QCoreApplication.translate("MainWindow", u"Single argument type", None))
        self.commandArgumentHandling.setItemText(2, QCoreApplication.translate("MainWindow", u"Argument type array", None))

        self.commandArgumentHandling.setCurrentText(QCoreApplication.translate("MainWindow", u"No arguments", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Comma separated argument types", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.command_tab), QCoreApplication.translate("MainWindow", u"Command Tree", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuGenerate.setTitle(QCoreApplication.translate("MainWindow", u"Generate", None))
    # retranslateUi

