/* Generated by InputHandler's /InputHandler/cli_gen_tool/cli_gen_tool.py version 1.0 */
/**
* @file functions.h
* @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
* @brief InputHandler autogenerated functions.h
* @version 1.0
* @date 2022-12-21
*
* @copyright Copyright (c) 2022
*/
/*
* Copyright (c) 2022 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* version 3 as published by the Free Software Foundation.
*/


#if !defined(__FUNCTIONS_H__)
    #define __FUNCTIONS_H__
    #include "InputHandler.h"
    

void unrecognized(UserInput* _inputHandler)
{
  
  Serial.println("unrecognized");
  _inputHandler->outputToStream(Serial);
}

void listCommands(UserInput* _inputHandler)
{
  _inputHandler->listCommands();
}

void listSettings(UserInput* _inputHandler)
{
  _inputHandler->listSettings(_inputHandler);
}

#endif
// end of file
