/* Generated by InputHandler's /InputHandler/cli_gen_tool/cli_gen_tool.py version 1.0 */
/**
* @file functions.h
* @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
* @brief InputHandler autogenerated functions.h
* @version 1.0
* @date 2022-12-27
*
* @copyright Copyright (c) 2022
*/
/*
* Copyright (c) 2022 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* version 3 as published by the Free Software Foundation.
*/


#if !defined(__FUNCTIONS_H__)
    #define __FUNCTIONS_H__
    #include "InputHandler.h"
    

/* InputHandler user return function prototypes */
void test(UserInput* _inputHandler);
void testa(UserInput* _inputHandler);
void testb(UserInput* _inputHandler);
void testc(UserInput* _inputHandler);

/* InputHandler function prototypes */
void unrecognized(UserInput* _inputHandler);
void listCommands(UserInput* _inputHandler);
void listSettings(UserInput* _inputHandler);
void test_2(UserInput* _inputHandler);
void testa_3(UserInput* _inputHandler);
void testd_5(UserInput* _inputHandler);
void teste_6(UserInput* _inputHandler);

#include "functions.cpp" // Generated InputHandler function definitions

#endif

// end of file
