/* Generated by InputHandler's /InputHandler/cli_gen_tool/cli_gen_tool.py version 1.0 */
/**
* @file functions.cpp
* @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
* @brief InputHandler autogenerated functions.cpp
* @version 1.0
* @date 2022-12-22
*
* @copyright Copyright (c) 2022
*/
/*
* Copyright (c) 2022 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* version 3 as published by the Free Software Foundation.
*/


#include "functions.h"
    
void unrecognized(UserInput* _inputHandler)
{
  _inputHandler->outputToStream(Serial);
}

void listCommands(UserInput* _inputHandler)
{
  _inputHandler->listCommands();
}

void listSettings(UserInput* _inputHandler)
{
  _inputHandler->listSettings(_inputHandler);
}


// end of file
