/* Generated by InputHandler's /InputHandler/cli_gen_tool/cli_gen_tool.py version 1.0 */
/**
* @file parameters.h
* @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
* @brief InputHandler autogenerated parameters.h
* @version 1.0
* @date 2022-12-21
*
* @copyright Copyright (c) 2022
*/
/*
* Copyright (c) 2022 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* version 3 as published by the Free Software Foundation.
*/


#if !defined(__PARAMETERS_H__)
    #define __PARAMETERS_H__
    #include "setup.h"
    

/**
   @brief CommandParameters struct for listCommands
*/
const PROGMEM CommandParameters listCommands_param[1] = 
{
    listCommands, // function pointer
    no_wildcards, // wildcard flag
    "listCommands", // command string
    12, // command string num characters
    0, // parent id
    0, // this command id (tree unique)
    0, // command depth
    0, // number of subcommands
    UI_ARG_HANDLING::no_args, // argument handling
    0, // minimum expected number of arguments
    0, // maximum expected number of arguments
    /* UITYPE arguments */
    {UITYPE::NO_ARGS}    
};
CommandConstructor listCommands_(listCommands_param); // listCommands_ command constructor

/**
   @brief CommandParameters struct for listSettings
*/
const PROGMEM CommandParameters listSettings_param[1] = 
{
    listSettings, // function pointer
    no_wildcards, // wildcard flag
    "listSettings", // command string
    12, // command string num characters
    0, // parent id
    0, // this command id (tree unique)
    0, // command depth
    0, // number of subcommands
    UI_ARG_HANDLING::no_args, // argument handling
    0, // minimum expected number of arguments
    0, // maximum expected number of arguments
    /* UITYPE arguments */
    {UITYPE::NO_ARGS}    
};
CommandConstructor listSettings_(listSettings_param); // listSettings_ command constructor


#endif
// end of file
