/* Generated by InputHandler's /InputHandler/cli_gen_tool/cli_gen_tool.py version 1.0 */
/**
* @file parameters.h
* @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
* @brief InputHandler autogenerated parameters.h
* @version 1.0
* @date 2022-12-28
*
* @copyright Copyright (c) 2022
*/
/*
* Copyright (c) 2022 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* version 3 as published by the Free Software Foundation.
*/


#if !defined(__PARAMETERS_H__)
    #define __PARAMETERS_H__
    #include "cli_setup.h"
    

/**
   @brief CommandParameters struct for listCommands
*/
const PROGMEM CommandParameters listCommands_param[1] = 
{
    listCommands, // function pointer
    no_wildcards, // wildcard flag
    "listCommands", // command string
    12, // command string num characters
    0, // parent id
    0, // this command id (tree unique)
    0, // command depth
    0, // number of subcommands
    UI_ARG_HANDLING::no_args, // argument handling
    0, // minimum expected number of arguments
    0, // maximum expected number of arguments
    /* UITYPE arguments */
    {UITYPE::NO_ARGS}    
};
CommandConstructor listCommands_(listCommands_param); // listCommands_ command constructor

/**
   @brief CommandParameters struct for listSettings
*/
const PROGMEM CommandParameters listSettings_param[1] = 
{
    listSettings, // function pointer
    no_wildcards, // wildcard flag
    "listSettings", // command string
    12, // command string num characters
    0, // parent id
    0, // this command id (tree unique)
    0, // command depth
    0, // number of subcommands
    UI_ARG_HANDLING::no_args, // argument handling
    0, // minimum expected number of arguments
    0, // maximum expected number of arguments
    /* UITYPE arguments */
    {UITYPE::NO_ARGS}    
};
CommandConstructor listSettings_(listSettings_param); // listSettings_ command constructor

/**
   @brief CommandParameters struct for testa_3
*/
const PROGMEM CommandParameters testa_3_param[1] = 
{
    testa_3, // function pointer
    no_wildcards, // wildcard flag
    "testa", // command string
    5, // command string num characters
    0, // parent id
    1, // this command id (tree unique)
    1, // command depth
    1, // number of subcommands
    UI_ARG_HANDLING::no_args, // argument handling
    0, // minimum expected number of arguments
    0, // maximum expected number of arguments
    /* UITYPE arguments */
    {UITYPE::NO_ARGS}    
};

/**
   @brief CommandParameters struct for testd_5
*/
const PROGMEM CommandParameters testd_5_param[1] = 
{
    testd_5, // function pointer
    no_wildcards, // wildcard flag
    "testd", // command string
    5, // command string num characters
    0, // parent id
    2, // this command id (tree unique)
    1, // command depth
    1, // number of subcommands
    UI_ARG_HANDLING::no_args, // argument handling
    0, // minimum expected number of arguments
    0, // maximum expected number of arguments
    /* UITYPE arguments */
    {UITYPE::NO_ARGS}    
};

/**
   @brief CommandParameters struct for teste_6
*/
const PROGMEM CommandParameters teste_6_param[1] = 
{
    teste_6, // function pointer
    no_wildcards, // wildcard flag
    "teste", // command string
    5, // command string num characters
    2, // parent id
    3, // this command id (tree unique)
    2, // command depth
    0, // number of subcommands
    UI_ARG_HANDLING::no_args, // argument handling
    0, // minimum expected number of arguments
    0, // maximum expected number of arguments
    /* UITYPE arguments */
    {UITYPE::NO_ARGS}    
};

/**
   @brief CommandParameters struct for test_2
*/
const PROGMEM CommandParameters test_2_param[1 /* root */ + 3 /* child(ren) */] = 
{
    {
      test_2, // function pointer
      no_wildcards, // wildcard flag
      "test", // command string
      4, // command string num characters
      0, // parent id
      0, // this command id (tree unique)
      0, // command depth
      2, // number of subcommands
      UI_ARG_HANDLING::no_args, // argument handling
      0, // minimum expected number of arguments
      0, // maximum expected number of arguments
      /* UITYPE arguments */
      {UITYPE::NO_ARGS}   
    },
    *testa_3_param, // pointer to testa_3_param
    *testd_5_param, // pointer to testd_5_param
    *teste_6_param  // pointer to teste_6_param
};
CommandConstructor test_2_(test_2_param, nprms(test_2_param), 2); // test_2_ command constructor

#endif

// end of file
