##
# @file config_h.py
# @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
# @brief config.h file generator
# @version 1.0.0
# @date 2023-05-22
# @copyright Copyright (c) 2023
# Copyright (C) 2023 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# version 3 as published by the Free Software Foundation.

import copy


class Config_H(object):
    """config.h generator

    Args:
        object (object): base object specialization
    """

    def __init__(self) -> None:
        """the constructor"""
        super(Config_H, self).__init__()

    # refresh the contents of config.h
    def config_h(self) -> str:
        """generates config.h for InputHandlers autogenerated CLI

        Args:
            item_string (str): code to highlight
            place_cursor (bool, optional): Place cursor on highlighted code if true. Defaults to False.
        """
        code_list = copy.deepcopy(self.input_config_file_lines)

        cfg_dict = self.cli_options["config"]["var"]
        # the contents at each key represents a config.h file line
        for key in cfg_dict:
            for item in cfg_dict[key]:
                sub_dict = cfg_dict[key][item]
                if sub_dict["value"] == True:
                    val = "true"
                elif sub_dict["value"] == False:
                    val = "false"
                else:
                    val = sub_dict["value"]
                line = f"    #define {str(item)} {val}"
                code_list[int(sub_dict["lineno"])] = line

        code_string = self.list_to_code_string(code_list)

        return code_string
        # end update_config_h


# end of file
