/* Generated by InputHandler's /InputHandler/cli_gen_tool/cli_gen_tool.py version 0.1 */
/**
  @file debugging.ino
  @author Douglas Quigg (dstroy0 dquigg123@gmail.com)
  @brief autogenerated InputHandler CLI setup.h
  @version 0.1
  @date 2022-07-09

  @copyright Copyright (c) 2022
*/
/*
  Copyright (c) 2022 Douglas Quigg (dstroy0) <dquigg123@gmail.com>
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License
  version 3 as published by the Free Software Foundation.
*/
#include <InputHandler.h>


char output_buffer[1] = {'\0'}; // output buffer

const PROGMEM IH_pname pname = ""; // process name
const PROGMEM IH_eol peol = "\r\n"; // process end of line char
const PROGMEM IH_input_cc pinputcc = "##"; // input control character sequence
const PROGMEM IH_wcc pwcc = "*"; // process wildcard char
const PROGMEM InputProcessDelimiterSequences pdelimseq = {
  2, // number of delimiter sequences
  {1, 1}, // delimiter sequence lens
  {" ", ","} // delimiter sequences
};

const PROGMEM InputProcessStartStopSequences pststpseq = {
  1.0, // num start stop sequence pairs
  {1, 1}, // start stop sequence lens
  {""", """} // start stop sequence pairs
};

const PROGMEM InputProcessParameters input_prm[1] = {
  &pname,
  &peol,
  &pinputcc,
  &pwcc,
  &pdelimseq,
  &pststpseq
};
UserInput inputHandler(input_prm, output_buffer, buffsz(output_buffer));

// default function, called if nothing matches or if there is an error
void unrecognized(UserInput* inputProcess)
{
  // error output
  inputProcess->outputToStream(Serial);
}

void InputHandler_setup()
{
  Serial.println(F("Setting up InputHandler..."));
  inputHandler.defaultFunction(unrecognized); // set default function, called when user input has no match or is not valid

  inputHandler.begin();                       // required.  returns true on success.

}
