name: Adafruit platforms (dynamic)

on:
  push:
    branches:
      - main
    paths:
      - "**/adafruit_platforms_dynamic_matrix.yml"
      - "**/examples/**"
      - "**/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"

jobs:
  set-up-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

  get-arduino-build-matrix:
    needs: set-up-environment
    runs-on: ubuntu-latest
    outputs:
      arduino-build-matrix: ${{ steps.set-arduino-matrix.outputs.arduino-build-matrix }}      
    steps:      
      # generate a build matrix for the arduino environment using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-arduino-matrix
        name: set-arduino-matrix
        uses: dstroy0/InputHandler/.github/generate_workflow_matrix.yml@main
        with:
          compiler: arduino
          platform: adafruit
        secrets: inherit
      
  get-platformio-build-matrix:
    needs: set-up-environment
    runs-on: ubuntu-latest
    outputs:
      platformio-build-matrix: ${{ steps.set-platformio-matrix.outputs.platformio-build-matrix }}
    steps:
      # generate a build matrix for the platformio environment using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-platformio-matrix
        name: set-platformio-matrix
        uses: dstroy0/InputHandler/.github/generate_workflow_matrix.yml@main
        with:
          compiler: platformio
          platform: adafruit

  build-library-arduino:
    needs: get-arduino-build-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # extract the boards that need to be built from the build matrix
        boards: ${{ fromJSON(needs.get-arduino-build-matrix.outputs.arduino-build-matrix)['boards'] }}
    steps:
      - uses: ./.github/compile_lib_using_arduino.yml
        with:
          compiler: arduino
          platform: adafruit
          platform-packages: |
            - source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
              name: "adafruit:samd"
          build-matrix: ${{ needs.get-arduino-build-matrix.outputs.arduino-build-matrix }}

  build-library-platformio:
    needs: get-platformio-build-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # extract the boards that need to be built from the build matrix
        boards: ${{ fromJSON(needs.get-platformio-build-matrix.outputs.platformio-build-matrix)['boards'] }}
    steps:
      - uses: ./.github/compile_lib_using_platformio.yml
        with:
          compiler: platformio
          platform: adafruit
          build-matrix: ${{ needs.get-platformio-build-matrix.outputs.platformio-build-matrix }}
