name: Adafruit platforms (dynamic)

on:
  push:
    branches:
      - main
    paths:
      - "**/adafruit_platforms_dynamic_matrix.yml"
      - "**/examples/**"
      - "**/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"

jobs:
  set-up-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

  get-arduino-build-matrix:
    needs: set-up-environment
    uses: ./.github/workflows/generate_workflow_matrix.yml
    with:
      compiler: arduino
      platform: adafruit

  get-platformio-build-matrix:
    needs: set-up-environment
    uses: ./.github/workflows/generate_workflow_matrix.yml
    with:
      compiler: platformio
      platform: adafruit

  build-library-arduino:
    needs: get-arduino-build-matrix
    uses: ./.github/workflows/compile_lib_using_arduino.yml
    with:
      compiler: arduino
      platform: adafruit
      platform-packages: |
        - source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
          name: "adafruit:samd"
      build-matrix: ${{ needs.get-arduino-build-matrix.outputs.build-matrix }}

  build-library-platformio:
    needs: get-platformio-build-matrix
    uses: ./.github/workflows/compile_lib_using_platformio.yml
    with:
      compiler: platformio
      platform: adafruit
      build-matrix: ${{ needs.get-platformio-build-matrix.outputs.build-matrix }}
