name: Adafruit platforms (dynamic)

on:
  push:
    branches:
      - main
    paths:
      - "**/adafruit_platforms_dynamic_matrix.yml"
      - "**/examples/**"
      - "**/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"

jobs:
  generate-job-matrices:
    runs-on: ubuntu-latest
    outputs:
      arduino-build-matrix: ${{ steps.set-arduino-matrix.outputs.arduino-build-matrix }}
      platformio-build-matrix: ${{ steps.set-platformio-matrix.outputs.platformio-build-matrix }}
    steps:
      
      # generate a build matrix for the arduino environment using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-arduino-matrix
        uses: ./.github/generate_workflow_matrix.yml
        with:
          compiler: arduino
          platform: adafruit

      # generate a build matrix for the platformio environment using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-platformio-matrix
        uses: ./.github/generate_workflow_matrix.yml
        with:
          compiler: platformio
          platform: adafruit
        

  build-library-arduino:
    needs: generate-job-matrices
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # extract the boards that need to be built from the build matrix
        boards: ${{ fromJSON(needs.generate-job-matrices.outputs.arduino-build-matrix)['boards'] }}
    steps:
      - uses: ./.github/compile_lib_using_arduino.yml
        with:
          compiler: arduino
          platform: adafruit
          platform-packages: |
            - source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
              name: "adafruit:samd"
          build-matrix: ${{ needs.generate-job-matrices.outputs.arduino-build-matrix }}

  build-library-platformio:
    needs: generate-job-matrices
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # extract the boards that need to be built from the build matrix
        boards: ${{ fromJSON(needs.generate-job-matrices.outputs.platformio-build-matrix)['boards'] }}
    steps:
      - uses: ./.github/compile_lib_using_platformio.yml
        with:
        compiler: platformio
        platform: adafruit
        build-matrix: ${{ needs.generate-job-matrices.outputs.arduino-build-matrix }}
      
