name: Build tool CLI Teensyduino Arduino

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/interfaces/test_output_cli/**"

jobs:
  build:    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - "teensy:avr:teensy2"
          - "teensy:avr:teensy30"
          - "teensy:avr:teensy31"
          - "teensy:avr:teensy35"
          - "teensy:avr:teensy36"
          - "teensy:avr:teensy40"
          - "teensy:avr:teensy41"
          - "teensy:avr:teensyLC"
          - "teensy:avr:teensyMM"
          - "teensy:avr:teensypp2"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          platforms: |
            - source-url: "https://www.pjrc.com/teensy/td_156/package_teensy_index.json"
              name: "teensy:avr"
          sketch-paths: ${{ matrix.example }}
          fqbn: ${{ matrix.fqbn }}
