name: cli_gen_tool build latest linux binary

on:
  push:
    branches:
      - main
    paths:
      - "**/cli_gen_tool_src/**"

  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/cli_gen_tool_src/**"

jobs:
  build-latest-linux-binary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r https://raw.githubusercontent.com/dstroy0/InputHandler/main/tools/cli_gen_tool_src/requirements.txt
          pip freeze

      - name: Update linux and install build dependencies
        run: |
          sudo add-apt-repository -y "deb http://cz.archive.ubuntu.com/ubuntu jammy main universe"
          sudo add-apt-repository -y "deb http://mirror.math.princeton.edu/pub/ubuntu/ jammy main universe"
          sudo apt-get -q update           
          sudo apt-get -y install libegl1
          sudo apt-get -y install libxkbcommon0
          sudo apt-get -y install libxkbcommon-x11-dev
          sudo apt-get -y install '^libxcb.*-dev'
          sudo apt-get -y install libx11-xcb-dev
          sudo apt-get -y install libglu1-mesa-dev
          sudo apt-get -y install libxrender-dev
          sudo apt-get -y install libxkbcommon-dev                
          sudo apt-get -y install libicu70          
          sudo apt-get -y install qt6-webengine-dev
          sudo apt-get -y install p7zip-full

      - name: get main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: get binaries
        uses: actions/checkout@v3
        with:
          ref: binaries

      - name: Build and zip binary, push to binaries branch
        run: |
          git config user.name "dstroy0"
          git config user.email "dstroy0@users.noreply.github.com"                                               

          git checkout binaries
          git checkout origin/main -- tools
          git add tools
          git commit -m "pull tools folder to binaries branch"          

          pyinstaller -y -F -w -i ./docs/img/Icon.ico ./tools/cli_gen_tool_src/cli_gen_tool.py --distpath ./latest/linux/
          7z a -tzip './latest/linux/cli_gen_tool.zip' './latest/linux/cli_gen_tool'
          7z t './latest/linux/cli_gen_tool.zip' *.

          git rm -r tools                  
          git add latest/linux/cli_gen_tool.zip
          git commit -m "built latest linux binary" -a
          git push -v
