name: cli_gen_tool build latest macos binary

on:
  push:
    branches:
      - main
    paths:
      - "**/cli_gen_tool_src/**"

  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/cli_gen_tool_src/**"

jobs:
  build-latest-macos-binary:
    runs-on: macos-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r https://raw.githubusercontent.com/dstroy0/InputHandler/main/tools/cli_gen_tool_src/requirements.txt
          pip install PyQt6-WebEngine
          pip3 install PyQt6-WebEngine
          pip3 install Pillow
          pip3 install PyQt6-WebEngine
          pip freeze

      - name: get main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: get binaries
        uses: actions/checkout@v3
        with:
          ref: binaries

      - name: Build and zip binary, push to binaries branch
        run: |
          git config user.name "dstroy0"
          git config user.email "dstroy0@users.noreply.github.com"                                               

          git checkout origin/binaries
          git checkout origin/main -- tools
          git checkout origin/main -- docs/img
          git add tools
          git add docs/img
          git commit -m "pull tools folder to binaries branch"          

          pyinstaller -y -F -w -i ./docs/img/Icon.ico ./tools/cli_gen_tool_src/cli_gen_tool.py --distpath ./latest/macos/
          7z a -tzip './latest/macos/cli_gen_tool.zip' './latest/macos/cli_gen_tool'
          7z t './latest/macos/cli_gen_tool.zip' *.               

          git rm -r tools                  
          git rm -r docs
          git add latest/macos/cli_gen_tool.zip
          git commit -m "built latest macos binary" -a
          git push origin HEAD:binaries
