name: Build tool test_output_cli Teensyduino (Arduino CLI)

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/interfaces/test_output_cli/**"

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: ["**/interfaces/test_output_cli/test_output_cli.ino"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check code formatting
        uses: per1234/artistic-style-action@main
        with:
          options-file-path: ./examples/examples_formatter.conf
          name-patterns: |
            - '*.ino'
            - '*.cpp'
            - '*.hpp'
            - '*.h'
          target-paths: ${{ matrix.example }}

  build:
    needs: check_formatting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - "teensy:avr:teensy2"
          - "teensy:avr:teensy30"
          - "teensy:avr:teensy31"
          - "teensy:avr:teensy35"
          - "teensy:avr:teensy36"
          - "teensy:avr:teensy40"
          - "teensy:avr:teensy41"
          - "teensy:avr:teensyLC"
          - "teensy:avr:teensyMM"
          - "teensy:avr:teensypp2"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          platforms: |
            - source-url: "https://www.pjrc.com/teensy/td_156/package_teensy_index.json"
              name: "teensy:avr"
          sketch-paths: ${{ matrix.example }}
          fqbn: ${{ matrix.fqbn }}
