name: Build Adafruit platforms Arduino

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"

jobs:  
  build:    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - "adafruit:samd:adafruit_blm_badge"
          - "adafruit:samd:adafruit_circuitplayground_m0"
          - "adafruit:samd:adafruit_crickit_m0"
          - "adafruit:samd:adafruit_feather_m0"
          - "adafruit:samd:adafruit_feather_m0_express"
          - "adafruit:samd:adafruit_feather_m4_can"
          - "adafruit:samd:adafruit_feather_m4"
          - "adafruit:samd:adafruit_gemma_m0"
          - "adafruit:samd:adafruit_grandcentral_m4"
          - "adafruit:samd:adafruit_hallowing"
          - "adafruit:samd:adafruit_hallowing_m4"
          - "adafruit:samd:adafruit_itsybitsy_m0"
          - "adafruit:samd:adafruit_itsybitsy_m4"
          - "adafruit:samd:adafruit_monster_m4sk"
          - "adafruit:samd:adafruit_matrixportal_m4"
          - "adafruit:samd:adafruit_metro_m0"
          - "adafruit:samd:adafruit_metro_m4"
          - "adafruit:samd:adafruit_metro_m4_airliftlite"
          - "adafruit:samd:adafruit_neokeytrinkey_m0"
          - "adafruit:samd:adafruit_proxlighttrinkey_m0"
          - "adafruit:samd:adafruit_pygamer_m4"
          - "adafruit:samd:adafruit_pyportal_m4"
          - "adafruit:samd:adafruit_pyportal_m4_titano"
          - "adafruit:samd:adafruit_qtpy_m0"
          - "adafruit:samd:adafruit_rotarytrinkey_m0"
          - "adafruit:samd:adafruit_slidetrinkey_m0"
          - "adafruit:samd:adafruit_trellis_m4"
          - "adafruit:samd:adafruit_trinket_m0"
          - "adafruit:samd:adafruit_pirkey"
          - "adafruit:samd:adafruit_pybadge_m4"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          platforms: |
            - source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
              name: "adafruit:samd"
          sketch-paths: ${{ matrix.example }}
          fqbn: ${{ matrix.fqbn }}
