name: cli_gen_tool build latest windows binary

on:
  push:
    branches:
      - main
    paths:
      - "**/cli_gen_tool_src/**"

  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/cli_gen_tool_src/**"

jobs:
  build-latest-windows-binary:
    runs-on: windows-latest

    steps:      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install wheel
          pip install -r ./tools/cli_gen_tool_src/requirements.txt          
          pip install PyQt6-WebEngine
          pip freeze

      - name: Build binary and push to binaries branch
      - uses: actions/checkout@v3
      - run: |     
          git config user.name "dstroy0"
          git config user.email "dstroy0@users.noreply.github.com"                                               
          git checkout binaries
          git checkout origin/main -- tools
          git add tools
          git commit -m "pull tools folder to binaries branch"          
          pyinstaller --paths './tools/resources/' -y -F -w -i ./docs/img/Icon.ico ./tools/cli_gen_tool_src/cli_gen_tool.py --distpath ./latest/windows/
          7z a -tzip './latest/windows/cli_gen_tool.zip' './latest/windows/cli_gen_tool.exe'
          7z t './latest/windows/cli_gen_tool.zip' *. -r          
          git rm tools
          git commit -m "built latest windows binary" -a
          git push -v
