name: Build tool test_output_cli (Arduino CLI)

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/interfaces/test_output_cli/**"

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: ["**/interfaces/test_output_cli/test_output_cli.ino"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check code formatting
        uses: per1234/artistic-style-action@main
        with:
          options-file-path: ./examples/examples_formatter.conf
          name-patterns: |
            - '*.ino'
            - '*.cpp'
            - '*.hpp'
            - '*.h'
          target-paths: ${{ matrix.example }}

  build:
    needs: check_formatting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - "arduino:avr:bt"
          - "arduino:avr:diecimila"
          - "arduino:avr:esplora"
          - "arduino:avr:ethernet"
          - "arduino:avr:fio"
          - "arduino:avr:gemma"
          - "arduino:avr:chiwawa"
          - "arduino:avr:leonardo"
          - "arduino:avr:leonardoeth"
          - "arduino:samd:mzero_bl"
          - "arduino:samd:mzero_pro_bl"
          - "arduino:samd:mzero_pro_bl_dbg"
          - "arduino:samd:mkrfox1200"
          - "arduino:samd:mkrgsm1400"
          - "arduino:samd:mkrnb1500"
          - "arduino:samd:mkrvidor4000"
          - "arduino:samd:mkrwan1300"
          - "arduino:samd:mkrwan1310"
          - "arduino:samd:mkrwifi1010"
          - "arduino:samd:mkr1000"
          - "arduino:samd:mkrzero"
          - "arduino:avr:megaADK"
          - "arduino:avr:mega"
          - "arduino:avr:micro"
          - "arduino:avr:mini"          
          - "arduino:avr:atmegang"
          - "arduino:avr:nano"
          - "arduino:mbed_nano:nano33ble"
          - "arduino:mbed_nano:nanorp2040connect"
          - "arduino:avr:pro"
          - "arduino:avr:robotControl"
          - "arduino:avr:robotMotor"
          - "arduino:samd:tian"
          - "arduino:avr:uno"
          - "arduino:avr:unomini"
          - "arduino:avr:unowifi"
          - "arduino:avr:yun"
          - "arduino:avr:yunmini"
          - "arduino:samd:arduino_zero_native"
          - "arduino:samd:arduino_zero_edbg"
          - "arduino:avr:lilypad"
          - "arduino:avr:LilyPadUSB"
          - "arduino:avr:one"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:          
          sketch-paths: ${{ matrix.example }}
          fqbn: ${{ matrix.fqbn }}
