name: cli_gen_tool build latest windows binary

on:
  push:
    branches:
      - main
    paths:
      - "**/cli_gen_tool_src/**"

  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/cli_gen_tool_src/**"

jobs:
  build-latest-windows-binary:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install wheel
          pip install -r ./tools/cli_gen_tool_src/requirements.txt          
          pip install PyQt6-WebEngine
          pip freeze

      - name: Build and zip binary
        shell: pwsh
        run: |
          echo ${{ github.workspace }}/tools/resources/ >> $GITHUB_PATH
          pyinstaller --paths '${{ github.workspace }}/tools/resources/' -y -F -w -i ./docs/img/Icon.ico ./tools/cli_gen_tool_src/cli_gen_tool.py --distpath ./tools/bin/latest/windows/
          7z a -tzip './tools/bin/latest/windows/cli_gen_tool.zip' './tools/bin/latest/windows/cli_gen_tool.exe'
          7z t './tools/bin/latest/windows/cli_gen_tool.zip' *. -r          
          rm './tools/bin/latest/windows/cli_gen_tool.exe'

      - name: Commit and push files
        id: commit
        shell: bash
        run: |
          git config --global user.email "dstroy0@users.noreply.github.com"
          git config --global user.name "dstroy0"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout binaries          
          git add ./tools/bin/latest/windows/cli_gen_tool.zip
          if [-z "$(git status --porcelain)"]; then
            echo "Unable to push"
          else
            git pull origin            
            git commit -m "cli_gen_tool windows binary latest" -a
            echo "Pushing"
            git push --force -v
          fi
