name: Build Teensyduino Platforms

on:
  push:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"

jobs:
  build:
    uses: ./.github/workflows/_build_platform.yml
    with:
      platform: teensyduino
      platform-packages-enabled: true
      platform-packages: |
        - source-url: "https://www.pjrc.com/teensy/td_156/package_teensy_index.json"
          name: "teensy:avr"

  # checkpoint
  build-teensyduino-success:
    runs-on: ubuntu-latest
    name: build-teensyduino-platforms-success
    needs: [build]
    steps:
      - name: echo
        run: echo Build Teensyduino platforms success!
