name: Build RPi Platforms (dynamic)

on:
  push:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"

jobs:
  build:
    uses: ./.github/workflows/_build_platform.yml
    with:
      platform: rpi
      platform-packages-enabled: false
      platform-packages: ""

  # checkpoint
  build-rpi-success:
    runs-on: ubuntu-latest
    name: build-rpi-platforms-success
    needs: [build]
    steps:
      - name: echo
        run: echo Build Raspberry Pi platforms success!
