name: Build tool test_output_cli (ESP PIO)

on:
  push:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/interfaces/test_output_cli/**"

jobs:
  build-examples-matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        examples: ["**/interfaces/test_output_cli/test_output_cli.ino"]

    steps:
      - uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          wget --no-check-certificate https://github.com/dstroy0/InputHandler/archive/main.zip -O /tmp/InputHandler-main.zip
          unzip /tmp/InputHandler-main.zip -d /tmp        
          ls

      - name: Build PlatformIO ESP32
        run: pio ci --lib="/tmp/InputHandler-main/"
          --board=esp32dev
          --board=huzzah
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.examples }}
