name: cli_gen_tool build latest binaries 

on: 
  push:
    branches:
      - main
    paths:
      - '**/cli_gen_tool_src/**'
  workflow_dispatch:
    branches:
      - main
    paths:
      - '**/cli_gen_tool_src/**'

jobs:
  build-latest-linux-binary:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Update linux and install build dependencies
        run: |
          sudo add-apt-repository -y "deb http://cz.archive.ubuntu.com/ubuntu jammy main universe"
          sudo add-apt-repository -y "deb http://mirror.math.princeton.edu/pub/ubuntu/ jammy main universe"
          sudo apt-get -q update           
          sudo apt-get -y install libegl1
          sudo apt-get -y install libxkbcommon0
          sudo apt-get -y install libxkbcommon-x11-dev
          sudo apt-get -y install '^libxcb.*-dev'
          sudo apt-get -y install libx11-xcb-dev
          sudo apt-get -y install libglu1-mesa-dev
          sudo apt-get -y install libxrender-dev
          sudo apt-get -y install libxkbcommon-dev                
          sudo apt-get -y install libicu70          
          sudo apt-get -y install qt6-webengine-dev
                                    
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r ./tools/cli_gen_tool_src/requirements.txt
          pip freeze                    
      
      - name: Build binary
        run: |                    
          pyinstaller -y --onefile ./tools/cli_gen_tool_src/cli_gen_tool.py --distpath ./tools/bin/latest/linux_macos/    
        
      - name: Commit and push files
        id: commit
        run: |
          git config --global user.email "dstroy0@users.noreply.github.com"
          git config --global user.name "dstroy0"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "Unable to push"
          else
            git commit -m "cli_gen_tool binary latest" -a
            echo "Pushing"
            git push
          fi
        shell: bash
                   

  build-latest-windows-binary:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: windows-latest

    steps:                                    
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r ./tools/cli_gen_tool_src/requirements.txt
          pip freeze                    
      
      - name: Add /downlevel/ to PATH
        run: |
          echo C:\\windows\\system32\\downlevel >> $GITHUB_PATH
          echo C:\\windows\\syswow64\\downlevel >> $GITHUB_PATH
        shell: bash

      - name: Build binary
        run: |                              
          pyinstaller -y --onefile ./tools/cli_gen_tool_src/cli_gen_tool.py --distpath ./tools/bin/latest/windows/    
        
      - name: Commit and push files
        id: commit
        run: |
          git config --global user.email "dstroy0@users.noreply.github.com"
          git config --global user.name "dstroy0"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "Unable to push"
          else
            git commit -m "cli_gen_tool binary latest" -a
            echo "Pushing"
            git push
          fi
        shell: bash
