name: Build ESP8266 Platforms

on:
  push:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"

jobs:
  build:
    uses: ./.github/workflows/_build_platform.yml
    with:
      platform: esp8266
      platform-packages-enabled: true
      platform-packages: |
        - source-url: "http://arduino.esp8266.com/stable/package_esp8266com_index.json"
          name: "esp8266"

  # checkpoint
  build-esp8266-success:
    runs-on: ubuntu-latest
    name: build-esp8266-platforms-success
    needs: [build]
    steps:
      - name: echo
        run: echo Build ESP8266 platforms success!
