name: cli_gen_tool build latest binaries CI 

on: 
  push:
    branches:
      - main
    paths:
      - tools/cli_gen_tool_src
  workflow_dispatch:
    branches:
      - main
    paths:
      - tools/cli_gen_tool_src

jobs:
  build-latest-binary:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Update linux and install build dependencies
        run: |
          apt-get update 
          apt-get install libegl1-dev
          apt-get install libxkbcommon0
          apt-get install libxkbcommon-x11-dev
          apt-get install '^libxcb.*-dev'
          apt-get install libx11-xcb-dev
          apt-get install libglu1-mesa-dev
          apt-get install libxrender-dev
          apt-get install libxkbcommon-dev      
          apt-get install libicu-dev
          apt-get install libicu70
          apt-get install qt6-webengine-dev

          

          
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r ./tools/cli_gen_tool_src/requirements.txt
          pip freeze                    
      
      - name: Build binary
        run: |          
          cd tools/cli_gen_tool_src/
          pyinstaller cli_gen_tool.py --distpath InputHandler/tools/bin/latest/    