name: Build Teensyduino examples (Arduino CLI)

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example:
          [
            "/examples/all_platforms/advanced/GetCommandFromStream/GetCommandFromStream.ino",
            "/examples/all_platforms/basic/GetCommandFromStream/GetCommandFromStream.ino",
            "/examples/all_platforms/advanced/NestedCommands/NestedCommands.ino",
            "/examples/all_platforms/advanced/WildcardCommands/WildcardCommands.ino",
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check code formatting
        uses: per1234/artistic-style-action@main
        with:
          options-file-path: ./examples/examples_formatter.conf
          name-patterns: |
            - '*.ino'
            - '*.cpp'
            - '*.hpp'
            - '*.h'
          target-paths: ${{ matrix.example }}

  build:
    needs: check_formatting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:         
          - "teensy:avr:teensy2"
          - "teensy:avr:teensy30"
          - "teensy:avr:teensy31"
          - "teensy:avr:teensy35"
          - "teensy:avr:teensy36"
          - "teensy:avr:teensy40"
          - "teensy:avr:teensy41"
          - "teensy:avr:teensyLC"
          - "teensy:avr:teensyMM"
          - "teensy:avr:teensypp2"    

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          platforms: |            
            - source-url: "https://www.pjrc.com/teensy/td_156/package_teensy_index.json"
              name: "teensy:avr"                          
          sketch-paths: ${{ matrix.example }}
          fqbn: ${{ matrix.fqbn }}
