name: cli_gen_tool build latest binaries CI 

on: 
  push:
    branches:
      - main
    paths:
      - tools/cli_gen_tool_src
  workflow_dispatch:
    branches:
      - main
    paths:
      - tools/cli_gen_tool_src

jobs:
  build-latest-binary:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Update linux and install build dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install libegl1
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libxcb-icccm4-dev
          sudo apt-get install libxcb-image0-dev
          sudo apt-get install libxcb-keysyms1-dev
          sudo apt-get install libxcb-randr0-dev
          sudo apt-get install libxcb-render-util0-dev
          sudo apt-get install libxcb-shape0-dev
          sudo apt-get -y install qt6-webengine-dev
          
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r ./tools/cli_gen_tool_src/requirements.txt
          pip freeze                    
      
      - name: Build binary
        run: |          
          cd tools/cli_gen_tool_src/
          pyinstaller cli_gen_tool.py --distpath InputHandler/tools/bin/latest/    