name: PlatformIO arduino CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/arduino/advanced/GetCommandFromStream/GetCommandFromStream.ino, 
                  examples/arduino/basic/GetCommandFromStream/GetCommandFromStream.ino]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        wget https://github.com/dstroy0/InputHandler/archive/main.zip -O /tmp/InputHandler-main.zip
        unzip /tmp/InputHandler-main.zip -d /tmp
    - name: Run PlatformIO
      run: pio ci --lib="." 
                  --lib="/tmp/InputHandler-main/" 
                  --board=teensy31                   
                  --board=teensy35 
                  --board=teensy36 
                  --board=teensy40 
                  --board=teensy41
                  --board=nanorp2040connect                    
                  
      env:
        PLATFORMIO_CI_SRC: ${{ matrix.example }}