name: Build tool test_output_cli (Arduino CLI)

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/interfaces/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/interfaces/test_output_cli/**"

jobs:
  check_formatting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        example: ["**/interfaces/test_output_cli/test_output_cli.ino"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check code formatting
        uses: per1234/artistic-style-action@main
        with:
          options-file-path: ./examples/examples_formatter.conf
          name-patterns: |
            - '*.ino'
            - '*.cpp'
            - '*.hpp'
            - '*.h'
          target-paths: ${{ matrix.example }}

  build:
    needs: check_formatting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        fqbn:
          - "esp8266:esp8266:gen4iodadafruit_crickit_m0"
          - "esp32:esp32:esp32cam"
          - "esp32:esp32:alksesp32"
          - "esp32:esp32:atmegazero_esp32s2"
          - "adafruit:samd:adafruit_blm_badge"
          - "arduino:avr:circuitplay32u4cat"
          - "arduino:samd:adafruit_circuitplayground_m0"
          - "adafruit:samd:adafruit_circuitplayground_m0"
          - "adafruit:samd:adafruit_crickit_m0"
          - "esp32:esp32:featheresp32"
          - "esp32:esp32:adafruit_feather_esp32_v2"
          - "esp32:esp32:adafruit_feather_esp32s2"
          - "esp32:esp32:adafruit_feather_esp32s2_tft"
          - "esp32:esp32:adafruit_feather_esp32s3"
          - "esp8266:esp8266:huzzah"
          - "adafruit:samd:adafruit_feather_m0"
          - "adafruit:samd:adafruit_feather_m0_express"
          - "adafruit:samd:adafruit_feather_m4_can"
          - "adafruit:samd:adafruit_feather_m4"
          - "esp32:esp32:adafruit_funhouse_esp32s2"
          - "adafruit:samd:adafruit_gemma_m0"
          - "adafruit:samd:adafruit_grandcentral_m4"
          - "adafruit:samd:adafruit_hallowing"
          - "adafruit:samd:adafruit_hallowing_m4"
          - "adafruit:samd:adafruit_itsybitsy_m0"
          - "adafruit:samd:adafruit_itsybitsy_m4"
          - "adafruit:samd:adafruit_monster_m4sk"
          - "esp32:esp32:adafruit_magtag29_esp32s2"
          - "adafruit:samd:adafruit_matrixportal_m4"
          - "esp32:esp32:adafruit_metro_esp32s2"
          - "adafruit:samd:adafruit_metro_m0"
          - "adafruit:samd:adafruit_metro_m4"
          - "adafruit:samd:adafruit_metro_m4_airliftlite"
          - "adafruit:samd:adafruit_neokeytrinkey_m0"
          - "adafruit:samd:adafruit_neotrinkey_m0"
          - "adafruit:samd:adafruit_proxlighttrinkey_m0"
          - "adafruit:samd:adafruit_pygamer_m4"
          - "adafruit:samd:adafruit_pyportal_m4"
          - "adafruit:samd:adafruit_pyportal_m4_titano"
          - "esp32:esp32:adafruit_qtpy_esp32_pico"
          - "esp32:esp32:adafruit_qtpy_esp32c3"
          - "esp32:esp32:adafruit_qtpy_esp32s2"
          - "esp32:esp32:adafruit_qtpy_esp32s3"
          - "adafruit:samd:adafruit_qtpy_m0"
          - "adafruit:samd:adafruit_rotarytrinkey_m0"
          - "adafruit:samd:adafruit_slidetrinkey_m0"
          - "adafruit:samd:adafruit_trellis_m4"
          - "adafruit:samd:adafruit_trinket_m0"
          - "adafruit:samd:adafruit_pirkey"
          - "adafruit:samd:adafruit_pybadge_airlift_m4"
          - "adafruit:samd:adafruit_pybadge_m4"
          - "esp32:esp32:AirM2M_CORE_ESP32C3"
          - "esp8266:esp8266:wifi_slot"
          - "esp8266:esp8266:arduino-esp8266"
          - "arduino:avr:bt"
          - "arduino:avr:diecimila"
          - "arduino:avr:esplora"
          - "arduino:avr:ethernet"
          - "arduino:avr:fio"
          - "arduino:avr:gemma"
          - "arduino:avr:chiwawa"
          - "arduino:avr:leonardo"
          - "arduino:avr:leonardoeth"
          - "arduino:samd:mzero_bl"
          - "arduino:samd:mzero_pro_bl"
          - "arduino:samd:mzero_pro_bl_dbg"
          - "arduino:samd:mkrfox1200"
          - "arduino:samd:mkrgsm1400"
          - "arduino:samd:mkrnb1500"
          - "arduino:samd:mkrvidor4000"
          - "arduino:samd:mkrwan1300"
          - "arduino:samd:mkrwan1310"
          - "arduino:samd:mkrwifi1010"
          - "arduino:samd:mkr1000"
          - "arduino:samd:mkrzero"
          - "arduino:avr:megaADK"
          - "arduino:avr:mega"
          - "arduino:avr:micro"
          - "arduino:avr:mini"
          - "arduino:samd:nano_33_iot"
          - "arduino:avr:atmegang"
          - "arduino:avr:nano"
          - "arduino:mbed_nano:nano33ble"
          - "arduino:mbed_nano:nanorp2040connect"
          - "arduino:avr:pro"
          - "arduino:avr:robotControl"
          - "arduino:avr:robotMotor"
          - "arduino:samd:tian"
          - "arduino:avr:uno"
          - "arduino:avr:unomini"
          - "arduino:avr:unowifi"
          - "arduino:avr:yun"
          - "arduino:avr:yunmini"
          - "arduino:samd:arduino_zero_native"
          - "arduino:samd:arduino_zero_edbg"
          - "esp32:esp32:bpi-bit"
          - "esp32:esp32:d-duino-32"
          - "esp8266:esp8266:espmxdevkit"
          - "esp32:esp32:esp32doit-devkit-v1"
          - "esp32:esp32:esp32doit-espduino"
          - "esp32:esp32:dpu_esp32"
          - "esp32:esp32:deneyapkart"
          - "esp32:esp32:deneyapkart1A"
          - "esp32:esp32:deneyapmini"
          - "esp32:esp32:ch_denky"
          - "esp8266:esp8266:oak"
          - "esp32:esp32:pocket_32"
          - "esp32:esp32:esp32"
          - "esp32:esp32:fm-devkit"
          - "esp32:esp32:pico32"
          - "esp32:esp32:esp32wroverkit"
          - "esp32:esp32:esp32wrover"
          - "esp32:esp32:esp32s3box"
          - "esp32:esp32:esp32s3usbotg"
          - "esp32:esp32:esp32da"
          - "esp32:esp32:esp32c3"
          - "esp32:esp32:esp32s2"
          - "esp32:esp32:esp32s2usb"
          - "esp32:esp32:esp32s3camlcd"
          - "esp32:esp32:esp32s3"
          - "esp32:esp32:esp32vn-iot-uno"
          - "esp8266:esp8266:espduino"
          - "esp32:esp32:espea32"
          - "esp8266:esp8266:espectro"
          - "esp32:esp32:espectro32"
          - "esp8266:esp8266:espino"
          - "esp8266:esp8266:espresso_lite_v1"
          - "esp8266:esp8266:espresso_lite_v2"
          - "esp32:esp32:ET-Board"
          - "esp32:esp32:esp320"
          - "esp32:esp32:firebeetle32"
          - "esp32:esp32:franzininho_wifi_esp32s2"
          - "esp32:esp32:franzininho_wifi_msc_esp32s2"
          - "esp32:esp32:frogboard"
          - "esp8266:esp8266:generic"
          - "esp8266:esp8266:esp8285"
          - "esp32:esp32:honeylemon"
          - "esp32:esp32:heltec_wifi_kit_32"
          - "esp32:esp32:heltec_wifi_lora_32"
          - "esp32:esp32:heltec_wifi_lora_32_V2"
          - "esp32:esp32:heltec_wireless_stick"
          - "esp32:esp32:heltec_wireless_stick_lite"
          - "esp32:esp32:hornbill32dev"
          - "esp32:esp32:hornbill32minima"
          - "esp32:esp32:imbrios-logsens-v1p1"
          - "esp32:esp32:OpenKB"
          - "esp8266:esp8266:sonoff"
          - "esp32:esp32:intorobot-fig"
          - "esp8266:esp8266:inventone"
          - "esp32:esp32:kb32"
          - "esp32:esp32:kits-edu"
          - "esp32:esp32:lolin_c3_mini"
          - "esp32:esp32:d32"
          - "esp32:esp32:d32_pro"
          - "esp32:esp32:lolin_s2_mini"
          - "esp32:esp32:lolin_s2_pico"
          - "esp8266:esp8266:d1_mini"
          - "esp8266:esp8266:d1_mini_clone"
          - "esp8266:esp8266:d1_mini_lite"
          - "esp8266:esp8266:d1_mini_pro"
          - "esp8266:esp8266:d1"
          - "esp32:esp32:mPython"
          - "esp8266:esp8266:agruminolemon"
          - "arduino:avr:lilypad"
          - "arduino:avr:LilyPadUSB"
          - "arduino:avr:one"
          - "esp32:esp32:lionbit"
          - "esp32:esp32:lopy"
          - "esp32:esp32:lopy4"
          - "esp32:esp32:m5stack-atom"
          - "esp32:esp32:m5stack-core-esp32"
          - "esp32:esp32:m5stack-core2"
          - "esp32:esp32:m5stack-coreink"
          - "esp32:esp32:m5stack-fire"
          - "esp32:esp32:m5stack-timer-cam"
          - "esp32:esp32:m5stick-c"
          - "esp32:esp32:mgbot-iotik32a"
          - "esp32:esp32:mgbot-iotik32b"
          - "esp32:esp32:mhetesp32devkit"
          - "esp32:esp32:mhetesp32minikit"
          - "esp32:esp32:magicbit"
          - "esp32:esp32:metro_esp-32"
          - "esp32:esp32:CoreESP32"
          - "esp32:esp32:nano32"
          - "esp32:esp32:node32s"
          - "esp8266:esp8266:nodemcu"
          - "esp8266:esp8266:nodemcuv2"
          - "esp32:esp32:nodemcu-32s"
          - "esp32:esp32:quantum"
          - "esp32:esp32:odroid_esp32"
          - "esp32:esp32:esp32-DevKitLipo"
          - "esp32:esp32:esp32-evb"
          - "esp32:esp32:esp32-gateway"
          - "esp32:esp32:esp32-poe"
          - "esp32:esp32:esp32-poe-iso"
          - "esp32:esp32:oroca_edubot"
          - "esp8266:esp8266:modwifi"
          - "esp32:esp32:onehorse32dev"
          - "esp8266:esp8266:phoenix_v1"
          - "esp8266:esp8266:phoenix_v2"
          - "esp32:esp32:piranha_esp-32"
          - "esp32:esp32:healthypi4"
          - "esp32:esp32:gpy"
          - "esp32:esp32:S_ODI_Ultra"
          - "esp8266:esp8266:eduinowifi"
          - "esp8266:esp8266:wiolink"
          - "esp32:esp32:sensesiot_weizen"
          - "esp32:esp32:wesp32"
          - "esp32:esp32:sonoff_dualr3"
          - "esp8266:esp8266:blynk"
          - "esp32:esp32:esp32micromod"
          - "esp32:esp32:esp32thing"
          - "esp32:esp32:esp32thing_plus"
          - "esp32:esp32:sparkfun_esp32s2_thing_plus"
          - "esp8266:esp8266:thing"
          - "esp8266:esp8266:thingdev"
          - "esp32:esp32:sparkfun_lora_gateway_1-channel"
          - "esp8266:esp8266:esp210"
          - "esp32:esp32:t-beam"
          - "esp32:esp32:ttgo-lora32"
          - "esp32:esp32:ttgo-t-oi-plus"
          - "esp32:esp32:twatch"
          - "esp32:esp32:ttgo-t1"
          - "esp32:esp32:ttgo-t7-v13-mini32"
          - "esp32:esp32:ttgo-t7-v14-mini32"
          - "esp8266:esp8266:espinotee"
          - "esp32:esp32:espino32"
          - "esp32:esp32:esp32-trueverit-iot-driver"
          - "esp32:esp32:esp32-trueverit-iot-driver-mkii"
          - "esp32:esp32:turta_iot_node"
          - "esp32:esp32:feathers2"
          - "esp32:esp32:feathers2neo"
          - "esp32:esp32:feathers3"
          - "esp32:esp32:pros3"
          - "esp32:esp32:rmp"
          - "esp32:esp32:tinypico"
          - "esp32:esp32:tinys2"
          - "esp32:esp32:tinys3"
          - "esp32:esp32:vintlabs-devkit-v1"
          - "esp32:esp32:d1_mini32"
          - "esp32:esp32:lolin32"
          - "esp32:esp32:lolin32-lite"
          - "esp32:esp32:wt32-eth01"
          - "esp32:esp32:watchy"
          - "esp32:esp32:WeMosBat"
          - "esp8266:esp8266:wifi_kit_8"
          - "esp8266:esp8266:wifiduino"
          - "esp32:esp32:wifiduino32"
          - "esp32:esp32:wipy3"
          - "esp32:esp32:widora-air"
          - "esp8266:esp8266:wifinfo"
          - "esp8266:esp8266:cw01"
          - "esp32:esp32:cw02"
          - "esp32:esp32:micros2"
          - "esp32:esp32:nina_w10"
          - "esp32:esp32:uPesy_wroom"
          - "esp32:esp32:uPesy_wrover"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          sketch-paths: ${{ matrix.example }}
          fqbn: ${{ matrix.fqbn }}
