name: cli_gen_tool build latest macos binary

on: 
  push:
    branches:
      - main
    paths:
      - '**/cli_gen_tool_src/**'
    
  workflow_dispatch:
    branches:
      - main
    paths:
      - '**/cli_gen_tool_src/**'

jobs:
  build-latest-linux-binary:
   
    runs-on: macos-latest

    steps:
                                          
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r ./tools/cli_gen_tool_src/requirements.txt
          pip freeze                    
      
      - name: Build and zip binary
        run: |                         
          pyinstaller -y -F -w -i ./docs/img/Icon.ico ./tools/cli_gen_tool_src/cli_gen_tool.py --distpath ./tools/bin/latest/macos/
          7z a -tzip './tools/bin/latest/macos/cli_gen_tool.zip' './tools/bin/latest/macos/cli_gen_tool'
          7z t './tools/bin/latest/macos/cli_gen_tool.zip' *.          
                  
      - name: Commit and push files
        id: commit
        run: |
          git config --global user.email "dstroy0@users.noreply.github.com"
          git config --global user.name "dstroy0"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout main
          git pull origin
          git add --all
          if [-z "$(git status --porcelain)"]; then
            echo "Unable to push"
          else
            git commit -m "cli_gen_tool linux binary latest" -a
            echo "Pushing"
            git push
          fi
        shell: bash 