name: Build lib with arduino

on:
  workflow_call:
    inputs:      
      platform-packages:
        required: true
        type: string
      build-matrix:
        required: true
        type: string

jobs:
  build-library-using-arduino:
    runs-on: ubuntu-latest
    env: 
      this-build-matrix: ${{ inputs.build-matrix }}
    strategy:      
      fail-fast: false
      matrix:
        # extract the boards that need to be built from the build matrix
        boards: ${{ fromJSON( $env.this-build-matrix )['boards'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile InputHandler examples
        uses: arduino/compile-sketches@main
        with:
          # get extra platform packages here
          platforms: |
            ${{ inputs.platform-packages }}
          # extract sketch paths from build matrix
          sketch-paths: ${{ toJSON(fromJSON( $this-build-matrix }} )['examples']) }}
          # get fqbn from build-arduino.strategy.matrix.boards
          fqbn: ${{ matrix.boards }}
