name: Compile with arduino

on:
  workflow_call:
    inputs:
      platform-packages-enabled:
        required: true
        type: boolean
      platform-packages:
        required: false
        type: string
      boards:
        required: true
        type: string
      examples:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # extract the boards that need to be built from the build matrix
        boards: ${{ fromJSON(inputs.boards) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile using arduino
        uses: arduino/compile-sketches@main
        with:          
          # extract sketch paths from build matrix
          sketch-paths: ${{ inputs.examples }}
          # get fqbn from build-arduino.strategy.matrix.boards
          fqbn: ${{ matrix.boards }}
        if: ${{ inputs.platform-packages-enabled == 'true' }}
          # get extra platform packages here
          platforms: |
            ${{ inputs.platform-packages }}
