name: Compile test cli using arduino

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  generate-job-matrices:
    runs-on: ubuntu-latest
    outputs:
      arduino-build-matrix: ${{ steps.set-arduino-matrix.outputs.arduino-build-matrix }}
      platformio-build-matrix: ${{ steps.set-platformio-matrix.outputs.platformio-build-matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # generate a build matrix for the arduino environment using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-arduino-matrix
        run: |
          echo -n "arduino-build-matrix=" >> $GITHUB_OUTPUT
          python supported_boards/generate_workflow_matrix.py -c arduino -p ${{ inputs.platform }} >> $GITHUB_OUTPUT

      # generate a build matrix for the platformio environment using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-platformio-matrix
        run: |
          echo -n "platformio-build-matrix=" >> $GITHUB_OUTPUT
          python supported_boards/generate_workflow_matrix.py -c platformio -p adafruit >> $GITHUB_OUTPUT

  build-arduino:
    needs: generate-job-matrices
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # extract the boards that need to be built from the build matrix
        boards: ${{ fromJSON(needs.generate-job-matrices.outputs.arduino-build-matrix)['boards'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          # get extra platform packages here
          platforms: |
            - source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
              name: "adafruit:samd"
          # extract sketch paths from build matrix
          sketch-paths: ${{ toJSON(fromJSON(needs.generate-job-matrices.outputs.arduino-build-matrix)['examples']) }}
          # get fqbn from build-arduino.strategy.matrix.boards
          fqbn: ${{ matrix.boards }}

      - name: Compile test cli
        uses: arduino/compile-sketches@main
        with:
          # get extra platform packages here
          platforms: |
            - source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
              name: "adafruit:samd"
          # extract cli_gen_tool test cli path from build matrix
          sketch-paths: ${{ toJSON(fromJSON(needs.generate-job-matrices.outputs.arduino-build-matrix)['test_cli']) }}
          # get fqbn from build-arduino.strategy.matrix.boards
          fqbn: ${{ matrix.boards }}
