name: Docs CI 

on: [push, release]

jobs:
  build-and-deploy-docs:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Update and install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libegl1
          sudo apt-get install graphviz
          sudo apt-get install graphviz-dev       
          sudo apt-get install clang   
          
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r ./cli_gen_tool/requirements.txt
          pip freeze                    
      
      - name: Build cli_gen_tool's Sphinx docs
        run: |
          sphinx-build -b html ./cli_gen_tool/docs/source ./docs_build/cli_gen_tool

      - name: Build lib Doxygen xml
        uses: mattnotmitt/doxygen-action@edge
        with:
          working-directory: '/github/workspace/'
          doxyfile-path: 'docs/Doxyfile'                        
      
      - name: Build InputHandler's Sphinx docs
        run: |
          sphinx-build -b html ./docs/source ./docs_build/lib
      
      - name: Deploy 🚀        
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # build dir needs to contain redirect to either index.html
          publish_dir: docs_build
          #destination_dir: docs