name: Build docs

on: 
  push:
    branches:
      - main
    paths:
      - '**/src/**'
      - '**/docs/**'
      - '**/tools/cli_gen_tool_src/**'
  workflow_dispatch:
    branches:
      - main
    paths:
      - '**/src/**'
      - '**/docs/**'
      - '**/tools/cli_gen_tool_src/**'
  release:
    branches:
      - release
    paths:
      - '**/src/**'
      - '**/docs/**'
      - '**/tools/cli_gen_tool_src/**'

jobs:
  build-and-deploy-docs:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - name: Update linux and install docs build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libegl1
          sudo apt-get install graphviz
          sudo apt-get install graphviz-dev       
          sudo apt-get install clang   
          
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -VV          
          pip install -r ./docs/build/requirements.txt
          pip freeze                    
      
      - name: Build cli_gen_tool's Sphinx docs
        run: |
          sphinx-build -b html ./docs/cli_gen_tool/source ./docs/build/cli_gen_tool

      - name: DOXYGEN_XML_BUILD (InputHandler's doxygen xml output)
        uses: mattnotmitt/doxygen-action@edge
        with:
          working-directory: '/github/workspace/'
          doxyfile-path: 'docs/lib/Doxyfile'                        
      
      - name: Build InputHandler's Sphinx docs
        run: |
          sphinx-build -b html ./docs/lib/source ./docs/build/lib
      
      - name: Deploy to gh-pages 🚀        
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # build dir needs to contain redirect to either index.html
          publish_dir: ./docs/build
          exclude_assets: 'requirements.txt'          