name: Doxygen CI 

on: [push, release]

jobs:
  build-doxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9
          wget https://www.doxygen.nl/files/doxygen-1.9.3.linux.bin.tar.gz
          tar -xvzf doxygen-1.9.3.linux.bin.tar.gz
          ln -s doxygen-1.9.3/bin/doxygen doxygen
      - name: get latest release version number
        id: latest_ver
        run: echo "::set-output name=release::$(awk -F "=" '/version/ {print $2}' library.properties)"
      - name: overwrite doxygen tags
        run: |
          touch doxygenAction
          echo "PROJECT_NUMBER = ${{ steps.latest_ver.outputs.release }}" >> doxygenAction
          echo "@INCLUDE = doxygenAction" >> Doxyfile
      - name: Generate Documentation
        run: ./doxygen ./docs/Doxyfile                        
      - name: Save doxygen docs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: "InputHandler_doxygen_docs"
          path: ${{ github.workspace }}/docs/html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs/html # The folder the action should deploy.
          target-folder: ./
