name: Doxygen CI 

on: [push, release]

jobs:
  build-doxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9
          sudo apt-get install doxygen          
      - name: get latest release version number
        id: latest_ver
        run: echo "::set-output name=release::$(awk -F "=" '/version/ {print $2}' library.properties)"
      - name: overwrite doxygen tags
        run: |
          touch doxygenAction
          echo "PROJECT_NUMBER = ${{ steps.latest_ver.outputs.release }}" >> doxygenAction
          echo "@INCLUDE = doxygenAction" >> Doxyfile
      - name: Generate Documentation
        run: ./doxygen ./docs/Doxyfile                        
      - name: Save doxygen docs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: "InputHandler_doxygen_docs"
          path: ${{ github.workspace }}/docs/html
      
