name: Doxygen CI

on: [push, pull-request, release]

jobs:
  build-doxygen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install Doxygen 1.9.2
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libclang-cpp1-9 libclang1-9
          wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz
          tar -xvzf doxygen-1.9.2.linux.bin.tar.gz
          ln -s doxygen-1.9.2/bin/doxygen doxygen
      - name: get latest release version number
        id: latest_ver
        run: echo "::set-output name=release::$(awk -F "=" '/version/ {print $2}' library.properties)"
      - name: overwrite doxygen tags
        run: |
          touch doxygenAction
          echo "PROJECT_NUMBER = ${{ steps.latest_ver.outputs.release }}" >> doxygenAction
          echo "@INCLUDE = doxygenAction" >> Doxyfile
      - name: Generate Documentation
        run: ./doxygen Doxyfile                        
      - name: Save doxygen docs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: "InputHandler_doxygen_docs"
          path: ${{ github.workspace }}/docs/html
      - name: Publish generated content to github pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/html
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
