name: ESP32 platforms (dynamic)

on:
  push:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/**"
      - "**/test_output_cli/**"

jobs:
  build:
    uses: ./.github/workflows/build_platform.yml
    with:
      platform: esp32
      platform-packages-enabled: true
      platform-packages: |
        - source-url: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"
          name: "esp32"

  # checkpoint
  build-adafruit-success:
    runs-on: ubuntu-latest
    name: build-adafruit-platforms-success
    needs: [build]
    steps:
      - name: echo
        run: echo Build ESP32 platforms success!
