name: ESP8266 platforms

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"
      - "**/interfaces/test_output_cli/**"
  workflow_dispatch:
    branches:
      - main
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"
      - "**/interfaces/test_output_cli/**"
  release:
    branches:
      - release
    paths:
      - "**/examples/all_platforms/basic/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/GetCommandFromStream/**"
      - "**/examples/all_platforms/advanced/MultiFile/**"
      - "**/examples/all_platforms/advanced/NestedCommands/**"
      - "**/examples/all_platforms/basic/WildcardCommands/**"
      - "**/interfaces/test_output_cli/**"

jobs:
  build-lib-arduino:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - "esp8266:esp8266:gen4iodadafruit_crickit_m0"
          - "esp8266:esp8266:huzzah"
          - "esp8266:esp8266:wifi_slot"
          - "esp8266:esp8266:arduino-esp8266"
          - "esp8266:esp8266:espmxdevkit"
          - "esp8266:esp8266:oak"
          - "esp8266:esp8266:espduino"
          - "esp8266:esp8266:espino"
          - "esp8266:esp8266:espresso_lite_v1"
          - "esp8266:esp8266:espresso_lite_v2"
          - "esp8266:esp8266:generic"
          - "esp8266:esp8266:esp8285"
          - "esp8266:esp8266:sonoff"
          - "esp8266:esp8266:inventone"
          - "esp8266:esp8266:d1_mini"
          - "esp8266:esp8266:d1_mini_clone"
          - "esp8266:esp8266:d1_mini_lite"
          - "esp8266:esp8266:d1_mini_pro"
          - "esp8266:esp8266:d1"
          - "esp8266:esp8266:agruminolemon"
          - "esp8266:esp8266:nodemcu"
          - "esp8266:esp8266:nodemcuv2"
          - "esp8266:esp8266:modwifi"
          - "esp8266:esp8266:phoenix_v1"
          - "esp8266:esp8266:phoenix_v2"
          - "esp8266:esp8266:eduinowifi"
          - "esp8266:esp8266:wiolink"
          - "esp8266:esp8266:blynk"
          - "esp8266:esp8266:thing"
          - "esp8266:esp8266:thingdev"
          - "esp8266:esp8266:esp210"
          - "esp8266:esp8266:espinotee"
          - "esp8266:esp8266:wifi_kit_8"
          - "esp8266:esp8266:wifiduino"
          - "esp8266:esp8266:wifinfo"
          - "esp8266:esp8266:cw01"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          platforms: |
            - source-url: "http://arduino.esp8266.com/stable/package_esp8266com_index.json"
              name: "esp8266:esp8266"
          sketch-paths: ${{ matrix.example }}
          fqbn: ${{ matrix.fqbn }}

  build-lib-pio:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples:
          [
            "examples/all_platforms/advanced/GetCommandFromStream/GetCommandFromStream.ino",
            "examples/all_platforms/basic/GetCommandFromStream/GetCommandFromStream.ino",
            "examples/all_platforms/advanced/NestedCommands/NestedCommands.ino",
            "examples/all_platforms/basic/WildcardCommands/WildcardCommands.ino",
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          wget --no-check-certificate https://github.com/dstroy0/InputHandler/archive/main.zip -O /tmp/InputHandler-main.zip
          unzip /tmp/InputHandler-main.zip -d /tmp        
          ls
      - name: Build library examples for esp8266 platforms with PlatformIO CI
        run: pio ci --lib="/tmp/InputHandler-main/"
          --board=huzzah
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.examples }}

  build-tool-cli-arduino:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fqbn:
          - "esp8266:esp8266:gen4iodadafruit_crickit_m0"
          - "esp8266:esp8266:huzzah"
          - "esp8266:esp8266:wifi_slot"
          - "esp8266:esp8266:arduino-esp8266"
          - "esp8266:esp8266:espmxdevkit"
          - "esp8266:esp8266:oak"
          - "esp8266:esp8266:espduino"
          - "esp8266:esp8266:espino"
          - "esp8266:esp8266:espresso_lite_v1"
          - "esp8266:esp8266:espresso_lite_v2"
          - "esp8266:esp8266:generic"
          - "esp8266:esp8266:esp8285"
          - "esp8266:esp8266:sonoff"
          - "esp8266:esp8266:inventone"
          - "esp8266:esp8266:d1_mini"
          - "esp8266:esp8266:d1_mini_clone"
          - "esp8266:esp8266:d1_mini_lite"
          - "esp8266:esp8266:d1_mini_pro"
          - "esp8266:esp8266:d1"
          - "esp8266:esp8266:agruminolemon"
          - "esp8266:esp8266:nodemcu"
          - "esp8266:esp8266:nodemcuv2"
          - "esp8266:esp8266:modwifi"
          - "esp8266:esp8266:phoenix_v1"
          - "esp8266:esp8266:phoenix_v2"
          - "esp8266:esp8266:eduinowifi"
          - "esp8266:esp8266:wiolink"
          - "esp8266:esp8266:blynk"
          - "esp8266:esp8266:thing"
          - "esp8266:esp8266:thingdev"
          - "esp8266:esp8266:esp210"
          - "esp8266:esp8266:espinotee"
          - "esp8266:esp8266:wifi_kit_8"
          - "esp8266:esp8266:wifiduino"
          - "esp8266:esp8266:wifinfo"
          - "esp8266:esp8266:cw01"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          platforms: |
            - source-url: "http://arduino.esp8266.com/stable/package_esp8266com_index.json"
              name: "esp8266:esp8266"
          sketch-paths: ${{ matrix.example }}
          fqbn: ${{ matrix.fqbn }}

  build-tool-cli-pio:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        examples: ["**/main.cpp"]
    steps:
      - uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          wget --no-check-certificate https://github.com/dstroy0/InputHandler/archive/main.zip -O /tmp/InputHandler-main.zip
          unzip /tmp/InputHandler-main.zip -d /tmp        
          echo moving to test interface directory     
          cd ../InputHandler/tools/interfaces/test_output_cli/pio_ci/                              
          ls -R
      - name: Build PlatformIO ESP8266
        run: pio ci
          --project-conf="tools/interfaces/test_output_cli/pio_ci/platformio.ini"
          --lib="tools/interfaces/test_output_cli/pio_ci/lib/CLI"
          --environment=esp8266
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.examples }}
