name: Generate changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
  release:
    branches:
      - release

jobs:
  changelog:
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0      
      - name: Generate changelog                
        run: |          
          npm install -g auto-changelog          
          git config user.name "dstroy0"
          git config user.email "dstroy0@users.noreply.github.com"                    
          ln -s library.json package.json
          npm version patch             
          auto-changelog -p          
          git add CHANGELOG.md library.json
          git rm package.json
          git commit -m "generate changelog" 
          git push origin HEAD:main

  # checkpoint
  generate-changelog-success:
    runs-on: ubuntu-latest
    name: generate-changelog-success
    needs: [changelog]
    steps:
      - name: echo
        run: echo generate CHANGELOG.md success!
