name: Generate changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
  release:
    branches:
      - release

jobs:
  changelog:
    runs-on: ubuntu-latest    
    steps:      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0      
      - name: Generate changelog                
        run: |          
          npm install -g auto-changelog          
          git config user.name "dstroy0"
          git config user.email "dstroy0@users.noreply.github.com"                    
          ln -s library.json package.json
          version=$(npm version patch)          
          auto-changelog -p -u -l 100 -b 100 --sort-commits date-desc                   
          rm README.md
          cat docs/LIB_README.md docs/LIB_CHANGELOG.md > README.md
          git rm package.json
          git add docs/LIB_CHANGELOG.md library.json README.md
          git commit -m "README.md $version" 
          git push origin HEAD:main

  # checkpoint
  generate-changelog-success:
    runs-on: ubuntu-latest
    name: generate-changelog-success
    needs: [changelog]
    steps:
      - name: echo
        run: echo generate LIB_CHANGELOG.md, update README.md success!
