name: Generate workflow sequences

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      compiler:
        required: true
        type: string
    outputs:
      boards:
        description: "The boards to build"
        value: ${{ jobs.generate-build-sequences.outputs.boards }}
      examples:
        description: "The examples to build"
        value: ${{ jobs.generate-build-sequences.outputs.examples }}
      test-cli:
        description: "The test cli to build"
        value: ${{ jobs.generate-build-sequences.outputs.test-cli }}
jobs:
  generate-build-matrix:
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.set-build-matrix.outputs.build-matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # generate a build matrix using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-build-matrix
        run: |
          build_matrix=$(python supported_boards/generate_workflow_matrix.py -c ${{ inputs.compiler }} -p ${{ inputs.platform }})
          echo "build-matrix=$build_matrix" >> $GITHUB_OUTPUT

  generate-build-sequences:
    needs: generate-build-matrix
    runs-on: ubuntu-latest
    outputs:
      boards: ${{ steps.set-build-sequences.outputs.boards }}
      examples: ${{ steps.set-build-sequences.outputs.examples }}
      test-cli: ${{ steps.set-build-sequences.outputs.test_cli }}
    steps:
      - id: set-build-sequences
        name: set-build-sequences
        env:
          boards: ${{ toJSON(fromJSON(needs.generate-build-matrix.outputs.build-matrix)['boards']) }}
          examples: ${{ toJSON(fromJSON(needs.generate-build-matrix.outputs.build-matrix)['examples']) }}
          test_cli: ${{ toJSON(fromJSON(needs.generate-build-matrix.outputs.build-matrix)['test_cli']) }}
        run: |
          $raw_boards=$(echo ${{ env.boards | tr -d '\n' }} )
          echo $raw_boards
          $translated_boards=$(echo $raw_boards | tr '\n' '')
          $boards_list=$(echo $translated_boards | sed -e 's/\[ //g' -e 's/\ ]//g' -e 's/\,//g')
          echo "board(s) to build:\n$boards_list"
          $examples_list=$(echo ${{ env.examples }} | tr '\n' '' | sed -e 's/\[ //g' -e 's/\ ]//g' -e 's/\,//g')
          echo "example path(s):\n$examples_list"
          $test_cli=$(echo ${{ env.test_cli }} | tr '\n' '' | sed -e 's/\[ //g' -e 's/\ ]//g' -e 's/\,//g')
          echo "test cli path:\n$test_cli"
          echo -n "boards=$boards_list" >> $GITHUB_OUTPUT
          echo -n "examples=$examples_list" >> $GITHUB_OUTPUT
          echo -n "test_cli=$test_cli_list" >> $GITHUB_OUTPUT
