name: Generate workflow sequences

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      compiler:
        required: true
        type: string
    outputs:
      boards:
        description: "The boards to build"
        value: ${{ jobs.generate-job-matrix.outputs.build-matrix }}

jobs:
  generate-build-sequences:
    runs-on: ubuntu-latest
    outputs:
      boards: ${{ steps.set-build-sequences.outputs.boards }}
      examples: ${{ steps.set-build-sequences.outputs.examples }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # generate a build matrix using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-build-sequences
        run: |
          build_matrix=$(python supported_boards/generate_workflow_matrix.py -c ${{ inputs.compiler }} -p ${{ inputs.platform }})
          echo -n "boards=" ; toJSON(fromJSON( $build_matrix )['boards']) >> $GITHUB_OUTPUT
          echo -n "examples=" ; toJSON(fromJSON( $build_matrix )['examples']) >> $GITHUB_OUTPUT
          

