name: Generate workflow matrix

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      compiler:
        required: true
        type: string
    outputs:
      build-matrix:
        description: "The build matrix for the job (boards and examples)"
        value: ${{ jobs.generate-job-matrix.outputs.build-matrix }}
      boards:
        description: "The boards to compile for the job"
        value: ${{ jobs.generate-job-matrix.outputs.boards }}
      examples:
        description: "The examples to compile for the job"
        value: ${{ jobs.generate-job-matrix.outputs.examples }}

jobs:
  generate-job-matrix:
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.set-matrix.outputs.build-matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # generate a build matrix using InputHandler/supported_boards/generate_workflow_matrix.py
      - id: set-matrix
        run: |
          echo -n "build-matrix=" >> $GITHUB_OUTPUT
          python supported_boards/generate_workflow_matrix.py -c ${{ inputs.compiler }} -p ${{ inputs.platform }} >> $GITHUB_OUTPUT
          echo ${{ outputs.build-matrix }}          

  generate-job-board-sequence:
    needs: generate-job-matrix
    runs-on: ubuntu-latest
    outputs:
      boards: ${{ steps.generate-job-board-sequence.outputs.boards }}
    steps:
      - id: set-boards
        run: |          
          echo "boards=fromJSON(toJSON( ${{ needs.generate-job-matrix.outputs.build-matrix }} )['boards'])" >> $GITHUB_ENV   
          echo "boards=${{env.boards }}" >> $GITHUB_OUTPUT

  generate-job-example-sequence:
    needs: generate-job-matrix
    runs-on: ubuntu-latest
    outputs:
      examples: ${{ steps.generate-job-example-sequence.outputs.examples }}
    steps:
      - id: set-examples
        run: |
          echo "examples=fromJSON(toJSON( ${{ needs.generate-job-matrix.outputs.build-matrix }} )['examples'])" >> $GITHUB_ENV
          echo "examples=${{ env.examples }}" >> $GITHUB_OUTPUT
