name: Lint InputHandler/src/** contrib
on:
  push:
    branches:
      - main
    paths: |
      - '**/src/**'
      - '**/lint_src_contributions.yml'
  workflow_dispatch:
    branches:
      - main
    paths: |
      - '**/src/**'

jobs:
  src-cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Arduino CLI (dependency)
        run: |
          export PATH="$GITHUB_WORKSPACE:$PATH"
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=$GITHUB_WORKSPACE sh

      - name: Lint src
        uses: shenxianpeng/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          ignore: docs | examples | tools | supported_boards
          lines-changed-only: false
          files-changed-only: false
          extra-args: |
            -w,
            -std=gnu++11,
            -fpermissive,
            -fno-exceptions,
            -ffunction-sections,
            -fdata-sections,
            -fno-threadsafe-statics,
            -Wno-error=narrowing

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1
